# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_reestr', '0004_auto_20171119_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
