# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_reestr', '0006_auto_20171119_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='hash_file',
            field=models.BinaryField(),
        ),
    ]
